version: '3'
services:
  web:
    image: brunoporto2702/web-simple:latest
    container_name: web-simple
    restart: always
    environment:
      - APP_ENV=production
    expose:
      - "8890"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deploy/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web